name: Handle Repository Dispatch

on:
  repository_dispatch:
    types: [trigger-bdk-python-test]

jobs:
  run-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: "Check out PR branch"
        uses: actions/checkout@v4
        with:
          submodules: recursive
          persist-credentials: false
          fetch-depth: 0

      - name: "Update bdk-ffi submodule to latest"
        run: |
          cd ../../bdk-ffi/ \
          && git fetch origin \
          && git checkout master \
          && git pull origin master \
          && echo "Testing commit: $(git log -1 --pretty=format:'%h %s (author: %cn)')"

      - name: "Cache"
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./target
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.toml','**/Cargo.lock') }}

      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: "Generate bdk.py and binaries"
        run: |
          bash ./scripts/generate-linux.sh  # Ensure this script generates bdk.py

      - name: "Run Tests"
        run: |
          python -m unittest discover --start "./tests/" --pattern "test_offline_*.py" --verbose
